#!/bin/bash

g_currentDir=$(dirname ${BASH_SOURCE[0]})
mkdir -p ${g_currentDir}/bin

arduino-cli compile \
            -b arduino:avr:uno \
            --warnings all \
            --libraries ${g_currentDir}/libs/ \
            ${g_currentDir} \
            --output ${g_currentDir}/bin/burger \
            $@
